#!/usr/bin/env ruby

require 'net/http/persistent'
require 'trollop'

require 'ruby-debug'
require 'progressbar'

module KeggFetcher
	@@host = 'http://www.genome.jp/'
	@@reaction = 'dbget-bin/www_bget?rn:'
	@@output_directory = 'Fetched_reaction_pages/'
	@@output_file = @@output_directory + 'reaction_entry_'
	
	def KeggFetcher.fetch_reaction_list(reactions, save_fetched_pages = true)
		progress = ProgressBar.new('Retrieving KEGG entries', reactions.length)
		http = Net::HTTP::Persistent.new
		reactions.each do |r|
			response = http.request URI @@host + @@reaction + r
			puts "Failed request for #{r};" unless response.class == Net::HTTPOK
			if save_fetched_pages
				Dir.mkdir @@output_directory unless Dir.exists? @@output_directory
				File.open(@@output_file + r + '.html','w') {|output| output.puts response.body}
			end
			progress.inc
		end 
		http.shutdown
		progress.finish
	end
end

if __FILE__ == $0
	args = Trollop::options {opt :file, 'Input KEGG reactions number list', :type=>String, :required=>true} 
	Trollop::die :file, "Provided reaction file does not exist" unless File.exist?(args[:file]) if args[:file]
	reactions = File.open(args[:file]).read.split
	KeggFetcher.fetch_reaction_list(reactions)
end

